DROP SCHEMA IF EXISTS tank CASCADE;

CREATE SCHEMA IF NOT EXISTS tank;


CREATE TABLE IF NOT EXISTS tank.player (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	shots BIGINT NOT NULL DEFAULT 0,
	hits BIGINT NOT NULL DEFAULT 0,
	misses BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tank.game (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	player1 BIGINT REFERENCES tank.player(id) NOT NULL,
	player2 BIGINT REFERENCES tank.player(id),
	date TIMESTAMP NOT NULL,
	status int NOT NULL DEFAULT 0
);
