INSERT INTO User (login, password) VALUES ('mlongo', '12345');
INSERT INTO User (login, password) VALUES ('amatta', 'abdef');
INSERT INTO User (login, password) VALUES ('fcarlucc', 'poiuy');
INSERT INTO User (login, password) VALUES ('lnicoter', 'wasdfr');
INSERT INTO User (login, password) VALUES ('mcenci', '09877');
INSERT INTO Chatroom (name, owner) VALUES ('Calcetto', 1);
INSERT INTO Chatroom (name, owner) VALUES ('Scuola', 2);
INSERT INTO Chatroom (name, owner) VALUES ('42Nextgen', 3);
INSERT INTO Chatroom (name, owner) VALUES ('Games', 4);
INSERT INTO Chatroom (name, owner) VALUES ('Discord', 5);
INSERT INTO Message (author, room, text, date) VALUES (1, 1, 'domani calcetto?', '15/05/2023');
INSERT INTO Message (author, room, text, date) VALUES (2, 1, 'non ce sto', '15/05/2023');
INSERT INTO Message (author, room, text, date) VALUES (3, 1, 'ma come non ce stai', '15/05/2023');
INSERT INTO Message (author, room, text, date) VALUES (4, 2, 'domani chi interroga?', '10/05/2023');
INSERT INTO Message (author, room, text, date) VALUES (5, 2, 'boh', '10/05/2023');
